apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: devops-app
type: Opaque
data:
  # echo -n "base64-encoded-32-char-key" | base64
  APP_KEY: YmFzZTY0OmJhc2U2NEVuY29kZWRMYXJhdmVsS2V5PT0=
  # Mêmes valeurs que postgres-secret
  DB_USERNAME: YXBwdXNlcg==
  DB_PASSWORD: U3Ryb25nUEBzc3cwcmQh