apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: devops-app
data:
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_URL: "http://backend-svc"
  DB_CONNECTION: "pgsql"
  DB_HOST: "postgres-svc"
  DB_PORT: "5432"
  DB_DATABASE: "appdb"
  CACHE_DRIVER: "file"
  SESSION_DRIVER: "file"
  QUEUE_CONNECTION: "sync"
  LOG_CHANNEL: "stderr"