apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: devops-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath          # Docker Desktop fournit "hostpath"
  resources:
    requests:
      storage: 5Gi