server {
    listen 80;
    root /var/www/public;
    index index.php;

    location / {
        try_files $uri $uri/ @php;
    }

    location @php {
        fastcgi_pass central_backend:9000;
        fastcgi_param SCRIPT_FILENAME /var/www/public/index.php;
        fastcgi_param PATH_INFO       $fastcgi_path_info;
        include fastcgi_params;
    }

    location ~ \.php$ {
        fastcgi_pass central_backend:9000;
        fastcgi_param SCRIPT_FILENAME /var/www/public/index.php;
        include fastcgi_params;
    }
}
